/*
 * Travel mircro service
 * Micro service to book a travel
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package uni.aznu.booking.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Generated;
import lombok.Data;

/**
 * BookTravelRequest
 */

@Data
@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-06T08:44:40.322365400+01:00[Europe/Warsaw]")
public class BookingRequest {
  @JsonProperty("person")
  private Person person = null;

  @JsonProperty("equipment")
  private Equipment equipment = null;

  @JsonProperty("visit")
  private Visit visit = null;

  @JsonProperty("paymentCard")
  private PaymentCard paymentCard = null;

  public BookingRequest person(Person person) {
    this.person = person;
    return this;
  }

  public BookingRequest equipment(Equipment equipment) {
    this.equipment = equipment;
    return this;
  }

  public BookingRequest visit(Visit visit) {
    this.visit = visit;
    return this;
  }

  public BookingRequest paymentCard(PaymentCard paymentCard) {
    this.paymentCard = paymentCard;
    return this;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookingRequest bookingRequest = (BookingRequest) o;
    return Objects.equals(this.person, bookingRequest.person) &&
        Objects.equals(this.equipment, bookingRequest.equipment) &&
        Objects.equals(this.visit, bookingRequest.visit) &&
        Objects.equals(this.paymentCard, bookingRequest.paymentCard);
  }

  @Override
  public int hashCode() {
    return Objects.hash(person, equipment, visit, paymentCard);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookTravelRequest {\n");
    
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    equipment: ").append(toIndentedString(equipment)).append("\n");
    sb.append("    visit: ").append(toIndentedString(visit)).append("\n");
    sb.append("    paymentCard: ").append(toIndentedString(paymentCard)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
